// AUTH
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_LOADED = "AUTH_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAIL = "AUTH_REGISTER_FAIL";
export const JOIN_NEWSLETTER_FAIL = "JOIN_NEWSLETTER_FAIL";
export const JOIN_NEWSLETTER_SUCCESS = "JOIN_NEWSLETTER_SUCCESS";
export const UNSUBSCRIBE_NEWSLETTER_FAIL = "UNSUBSCRIBE_NEWSLETTER_FAIL";
export const UNSUBSCRIBE_NEWSLETTER_SUCCESS = "UNSUBSCRIBE_NEWSLETTER_SUCCESS";
export const PASSWORD_FORGOT_0_FAIL = "PASSWORD_FORGOT_0_FAIL";
export const PASSWORD_FORGOT_0_SUCCESS = "PASSWORD_FORGOT_0_SUCCESS";
export const PASSWORD_FORGOT_1_FAIL = "PASSWORD_FORGOT_1_FAIL";
export const PASSWORD_FORGOT_1_SUCCESS = "PASSWORD_FORGOT_1_SUCCESS";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const CONTACT_FAIL = "CONTACT_FAIL";
export const CONTACT_SUCCESS = "CONTACT_SUCCESS";
export const CHECK_VISITED_PAGE_FAIL = "CHECK_VISITED_PAGE_FAIL";
export const CHECK_VISITED_PAGE_SUCCESS = "CHECK_VISITED_PAGE_SUCCESS";
export const RETRIEVE_FAQS_FAIL = "RETRIEVE_FAQS_FAIL";
export const RETRIEVE_FAQS_SUCCESS = "RETRIEVE_FAQS_SUCCESS";
export const ASK_FAQ_FAIL = "ASK_FAQ_FAIL";
export const ASK_FAQ_SUCCESS = "ASK_FAQ_SUCCESS";

// ENDPOINT
export const ENDPOINT_CREATE_SUCCESS = "ENDPOINT_CREATE_SUCCESS";
export const ENDPOINT_CREATE_FAIL = "ENDPOINT_CREATE_FAIL";
export const ENDPOINT_UPDATE_SUCCESS = "ENDPOINT_UPDATE_SUCCESS";
export const ENDPOINT_UPDATE_FAIL = "ENDPOINT_UPDATE_FAIL";
export const RETRIEVE_ENDPOINTS_SUCCESS = "RETRIEVE_ENDPOINTS_SUCCESS";
export const RETRIEVE_ENDPOINTS_FAIL = "RETRIEVE_ENDPOINTS_FAIL";
export const  REMOVE_ENDPOINT_SUCCESS = "REMOVE_ENDPOINT_SUCCESS";
export const  REMOVE_ENDPOINT_FAIL = "REMOVE_ENDPOINT_FAIL";
export const RETRIEVE_ENDPOINT_SUCCESS = "RETRIEVE_ENDPOINT_SUCCESS";
export const RETRIEVE_ENDPOINT_FAIL = "RETRIEVE_ENDPOINT_FAIL";
export const UPDATE_ENDPOINT_SUCCESS = "UPDATE_ENDPOINT_SUCCESS";
export const UPDATE_ENDPOINT_FAIL = "UPDATE_ENDPOINT_FAIL";
export const RETRIEVE_ENDPOINTS_VALIDATIONS_FAIL = "RETRIEVE_ENDPOINTS_VALIDATIONS_FAIL";
export const RETRIEVE_ENDPOINTS_VALIDATIONS_SUCCESS = "RETRIEVE_ENDPOINTS_VALIDATIONS_SUCCESS";

// PROJECT
export const PROJECT_CREATE_SUCCESS = "PROJECT_CREATE_SUCCESS";
export const PROJECT_CREATE_FAIL = "PROJECT_CREATE_FAIL";
export const RETRIEVE_PROJECTS_SUCCESS = "RETRIEVE_PROJECTS_SUCCESS";
export const RETRIEVE_PROJECTS_FAIL = "RETRIEVE_PROJECTS_FAIL";
export const RETRIEVE_PROJECT_SUCCESS = "RETRIEVE_PROJECT_SUCCESS";
export const RETRIEVE_PROJECT_FAIL = "RETRIEVE_PROJECT_FAIL";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_FAIL = "UPDATE_PROJECT_FAIL";
export const REMOVE_PROJECT_SUCCESS = "REMOVE_PROJECT_SUCCESS";
export const REMOVE_PROJECT_FAIL = "REMOVE_PROJECT_FAIL";
export const UPDATE_PROJECT_SETTINGS_FAIL = "UPDATE_PROJECT_SETTINGS_FAIL";
export const UPDATE_PROJECT_SETTINGS_SUCCESS = "UPDATE_PROJECT_SETTINGS_SUCCESS";
export const RETRIEVE_PROJECT_SETTINGS_FAIL = "RETRIEVE_PROJECT_SETTINGS_FAIL";
export const RETRIEVE_PROJECT_SETTINGS_SUCCESS = "RETRIEVE_PROJECT_SETTINGS_SUCCESS";
export const ACTIVATE_PROJECT_SUCCESS = "  ACTIVATE_PROJECT_SUCCESS";
export const ACTIVATE_PROJECT_FAIL = "  ACTIVATE_PROJECT_FAIL";
export const CREATE_PROJECT_FROM_TEMPLATE_FAIL = "CREATE_PROJECT_FROM_TEMPLATE_FAIL";
export const CREATE_PROJECT_FROM_TEMPLATE_SUCCESS = "CREATE_PROJECT_FROM_TEMPLATE_SUCCESS";

// TEMPLATE
export const REMOVE_TEMPLATE_FAIL = "REMOVE_TEMPLATE_FAIL";
export const REMOVE_TEMPLATE_SUCCESS = "REMOVE_TEMPLATE_SUCCESS";
export const RETRIEVE_TEMPLATES_FAIL = "RETRIEVE_TEMPLATES_FAIL";
export const RETRIEVE_TEMPLATES_SUCCESS = "RETRIEVE_TEMPLATES_SUCCESS";
export const CREATE_TEMPLATE_FAIL = "CREATE_TEMPLATE_FAIL";
export const CREATE_TEMPLATE_SUCCESS = "CREATE_TEMPLATE_SUCCESS";
export const ADD_SHARE_TEMPLATE_FAIL = "ADD_SHARE_TEMPLATE_FAIL";
export const ADD_SHARE_TEMPLATE_SUCCESS = "ADD_SHARE_TEMPLATE_SUCCESS";
export const UPDATE_TEMPLATE_FAIL = "UPDATE_TEMPLATE_FAIL";
export const UPDATE_TEMPLATE_SUCCESS = "UPDATE_TEMPLATE_SUCCESS";

// APP
export const RETRIEVE_APPS_SUCCESS = "RETRIEVE_APPS_SUCCESS";
export const RETRIEVE_APPS_FAIL = "RETRIEVE_APPS_FAIL";
export const APP_CREATE_FAIL = "APP_CREATE_FAIL";
export const APP_CREATE_SUCCESS = "APP_CREATE_SUCCESS";
export const REMOVE_APP_FAIL = "REMOVE_APP_FAIL";
export const REMOVE_APP_SUCCESS = "REMOVE_APP_SUCCESS";

// MODEL
export const MODEL_CREATE_SUCCESS = "MODEL_CREATE_SUCCESS";
export const MODEL_CREATE_FAIL = "MODEL_CREATE_FAIL";
export const RETRIEVE_MODELS_SUCCESS = "RETRIEVE_MODELS_SUCCESS";
export const RETRIEVE_MODELS_FAIL = "RETRIEVE_MODELS_FAIL";
export const REMOVE_MODEL_SUCCESS = "REMOVE_MODEL_SUCCESS";
export const REMOVE_MODEL_FAIL = "REMOVE_MODEL_FAIL";
export const REMOVE_MODEL_FIELD_SUCCESS = "REMOVE_MODEL_FIELD_SUCCESS";
export const REMOVE_MODEL_FIELD_FAIL = "REMOVE_MODEL_FIELD_FAIL";
export const UPDATE_MODEL_FAIL = "UPDATE_MODEL_FAIL";
export const UPDATE_MODEL_SUCCESS = "UPDATE_MODEL_SUCCESS";
export const RETRIEVE_FOREIGN_KEYS_FAIL = "RETRIEVE_FOREIGN_KEYS_FAIL";
export const RETRIEVE_FOREIGN_KEYS_SUCCESS = "RETRIEVE_FOREIGN_KEYS_SUCCESS";

// USER
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_CREATE_FAIL = "USER_CREATE_FAIL";
export const RETRIEVE_USER_SUCCESS = "RETRIEVE_USER_SUCCESS";
export const RETRIEVE_USER_FAIL = "RETRIEVE_USER_FAIL";
export const RETRIEVE_MODEL_SUCCESS = "RETRIEVE_MODEL_SUCCESS";
export const RETRIEVE_MODEL_FAIL = "RETRIEVE_MODEL_FAIL";

// ACCOUNT
export const ACCOUNT_LOAD_SUCCESS = "ACCOUNT_LOAD_SUCCESS";
export const ACCOUNT_LOAD_FAIL = "ACCOUNT_LOAD_FAIL";
export const ACCOUNT_UPDATE_SUCCESS = "ACCOUNT_UPDATE_SUCCESS";
export const ACCOUNT_UPDATE_FAIL = "ACCOUNT_UPDATE_FAIL";
// THUMBNAIL
export const ACCOUNT_THUMBNAIL_REMOVE_SUCCESS = "ACCOUNT_THUMBNAIL_REMOVE_SUCCESS";
export const ACCOUNT_THUMBNAIL_REMOVE_FAIL = "ACCOUNT_THUMBNAIL_REMOVE_FAIL";
export const ACCOUNT_THUMBNAIL_UPDATE_SUCCESS = "ACCOUNT_THUMBNAIL_UPDATE_SUCCESS";
export const ACCOUNT_THUMBNAIL_UPDATE_FAIL = "ACCOUNT_THUMBNAIL_UPDATE_FAIL";
// TEAM
export const JOIN_TEAM_FAIL = "JOIN_TEAM_FAIL";
export const JOIN_TEAM_SUCCESS = "JOIN_TEAM_SUCCESS";
export const CREATE_NEW_TEAM_FAIL = "CREATE_NEW_TEAM_FAIL";
export const CREATE_NEW_TEAM_SUCCESS = "CREATE_NEW_TEAM_SUCCESS";

// NOTIFICATION
export const NOTIFICATION_SENT = "NOTIFICATION_SENT";
export const OPEN_INFOBAR = "OPEN_INFOBAR";
export const CLOSE_INFOBAR = "CLOSE_INFOBAR";
export const GET_LAST_INFOBAR = "GET_LAST_INFOBAR";
export const NAVBAR_OPTIONS_SET = "NAVBAR_OPTIONS_SET";
export const MODAL_INFO_SET = "MODAL_INFO_SET";
export const MODAL_INFO_RESET = "MODAL_INFO_RESET";

