# Generated by Django 4.1 on 2022-12-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_architecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='architecture',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='architecture',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='architecture',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
