# Generated by Django 4.1 on 2022-11-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='github',
        ),
        migrations.RemoveField(
            model_name='user',
            name='initial_thumbnail',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='initial_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='users/thumbnails'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='users/thumbnails'),
        ),
    ]
