# Generated by Django 4.1 on 2022-12-15 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_architecture_description_architecture_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='architecture',
            old_name='grid',
            new_name='viewport',
        ),
    ]
